export const siteConfig = {
  name: "Darshan BS - Backend Engineer",
  authorName: "Darshan BS",
  username: "darshanbs04",
  jobTitle: "Backend Engineer",
  email: "darshanbs04@gmail.com",
  phone: "+91 9110442362",
  location: "Bengaluru, India",
  description:
    "Darshan BS — Backend Engineer specializing in high-throughput distributed systems with Java, Spring Boot, Apache Kafka, and MySQL. Architecting in-house platforms scaling to 300K–500K daily transactions.",
  url: "https://personal-portfolio-teal-eight-52.vercel.app",
  links: {
    twitter: "",
    github: "",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-monogram.svg",
  iconIco: "/favicon.ico",
  logoIcon: "/profile-monogram.svg",
  keywords: [
    "Darshan BS",
    "Backend Engineer",
    "Software Engineer",
    "Java Developer",
    "Spring Boot",
    "Apache Kafka",
    "MySQL",
    "Redis",
    "AWS",
    "Distributed Systems",
    "Event-Driven Architecture",
    "Microservices",
    "DTDC Express",
    "Bengaluru",
  ],
};
